# -*- coding: utf-8 -*-
"""dasafio-bootcamp-azure.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cWBf1ayZMB8rvxpxv2c6hVQlafmVXRZX
"""

# prompt: pip install requests python-docx

!pip install requests python-docx

import requests
from docx import Document
import os

subscription_key = 'YOUR_SUBSCRIPTION'
endpoint = 'https://api.cognitive.microsofttranslator.com'
location = 'eastus2'
target_language = 'pt-br'

def translate_text(text, target_language):
  path: str = '/translate'
  constructed_url = endpoint + path
  headers = {
      'Ocp-Apim-Subscription-Key': subscription_key,
      'Ocp-Apim-Subscription-Region': location,
      'Content-type': 'application/json',
      'X-ClientTraceId': str(os.urandom(16))
  }
  body = [{
      'text': text
  }]
  params = {
      'api-version': '3.0',
      'from': 'en',
      'to': target_language
  }

  requests.request('POST', constructed_url, headers=headers, json=body, params=params)
  response = request.json()
  return response[0]['translations'][0]['text']

def translate_document(input_file, output_file):
  doc = Document(input_file)
  full_text =[]

  for paragraph in doc.paragraphs:
    translate_text = translate_text(paragraph.text, target_language)
    full_text.append(translate_text)

  with open(output_file, 'w', encoding='utf-8') as f:
    f.write('\n'.join(full_text))